### PR TITLE
fixed onSelect bug

### LINKED ISSUE #139: OnEdit: TypeError: [x] is not a function
Hello, 
  First, thank you for creating this library.  I'm hoping it saves me from building a custom json editing solution.  It looks like when 'OnEdit' of provided as a prop when you click on the value portion of a property (not object or array) an error is thrown.  
Below is from your demo site:
https://mac-s-g.github.io/react-json-view/demo/dist/
Based on the documentation's mention of double click opening the edit text area I suspect it may be that logic that isn't working.  Let me know if more information is required or if I'm just not doing it correctly.
onediteror

**EDIT**
I was looking through the documentation and I saw there is one last 'on' command, 'onSelect'.  If I enable that along with the other 'on' commands I no longer get the error.  So good news I won't get hammered by my team for errors and I can still use the library.  I hope that information is helpful.

### PR DESCRIPTION
**Pull request by mac-s-g**
fixes #139

### CODE REVIEW

File: src/js/components/VariableEditor.js [hunk 1]
```diff
@@ -32,307 +37,389 @@ class VariableEditor extends React.Component {
...
+                            </span>
+                            <span style={{ verticalAlign: "top" }}>"</span>
+                        </span>
+                        <span {...Theme(theme, "colon")}>:</span>
+                    </span>
+                )}
+                <div
+                    class="variable-value"
+                    onClick={
+                        onSelect === false && onEdit === false
```
Comment (mac-s-g) [inline src/js/components/VariableEditor.js]: this is the only functional change to this file.  

the rest was updated because I started using [prettier](https://github.com/prettier/prettier) sublime plugin which auto-formats on save
